### PR TITLE
Finishing touches

### PR DESCRIPTION
**Pull request by pwentz**
Seed update, minor styling fixes.

### CODE REVIEW

**Comment by dtinianow** [comment]
Everything looks good and is working! Push it

**Comment by Yoyo2Code** [comment]
Nice clean up on the styling. The flash messages are really clear.

**Comment by Automatic365** [comment]
I really like how this all came together

**Comment by dtinianow** [comment]
For posterity sake, I'll note here that we cleaned up all this styling together

**Pull request merged**
