### PR TITLE
Development

### PR DESCRIPTION
**Pull request by dtinianow**
This commit encompasses all of our user stories from our most recent client meeting with Sally last Thursday. These user stories cover user and visitor functionality

### CODE REVIEW

**Comment by dtinianow** [comment]
This commit encompasses all of our user stories from our most recent client meeting with Sally last Thursday.  These user stories cover user and visitor functionality

**Comment by Automatic365** [comment]
I don't think a rebase is necessary here

**Comment by Yoyo2Code** [comment]
We can merge development into master now.

**Comment by dtinianow** [comment]
Great work guys, our next user stories will focus on business admin and platform admin functionality

**Pull request merged**
